services:
  assembler:
    build:
      context: ./docker
      dockerfile: Dockerfile.assembler
    privileged: true
    environment:
      - FLASHBERRY_CFG=/work/flashberry.yml
    volumes:
      - ./:/work
      - /dev:/dev
      - /run/udev:/run/udev
    working_dir: /work

  flasher:
    build:
      context: ./docker
      dockerfile: Dockerfile.flasher
    privileged: true
    volumes:
      - ./:/work
      - /dev:/dev
    working_dir: /work
